### ISSUE TITLE
Allow glass panes and iron bars to connect to vertical slabs

### ISSUE THREAD

**Issue by TheCommandoChicken** [CiFru/AdditionalBlocksVerticalEdition#1]

**Comment by CiFru** [comment]
Thank you for the suggestion. Unfortunately, I'm not really inclined to add this feature.
Vertical slabs are based at the edges of a block, while panes are based in the middle.
This would make it that panes stick out one pixel, relative to the vertical slab. That would make it both aesthetically unpleasing and cause the borders of the pane to be invisible, so players can see that the pane has no side. If you were to add a side to the pane, it could cause some performance issues. 
See the added file for clarification.
![Untitled](https://github.com/CiFru/AdditionalBlocksVerticalEdition/assets/77511337/74efd98c-3cb3-46c0-8ba3-82b7a0b369b1)
